name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: ray-di/.github/.github/workflows/continuous-integration.yml@windows
    with:
      old_stable: '["7.0", "7.1", "7.2", "7.3", "7.4", "8.0", "8.1", "8.2", "8.3"]'
      current_stable: 8.4
